

CUDA_VISIBLE_DEVICES=0 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.6 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.6.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.6.pth

CUDA_VISIBLE_DEVICES=0 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.55 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.55.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.55.pth

CUDA_VISIBLE_DEVICES=0 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.5 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.5.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.5.pth

CUDA_VISIBLE_DEVICES=1 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.45 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.45.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.45.pth

CUDA_VISIBLE_DEVICES=2 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.4 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.4.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.4.pth

CUDA_VISIBLE_DEVICES=3 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.35 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.35.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.35.pth

CUDA_VISIBLE_DEVICES=0 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.3 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.3.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.3.pth

CUDA_VISIBLE_DEVICES=0 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.25 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.25.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.25.pth

CUDA_VISIBLE_DEVICES=0 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.2 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.2.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.2.pth

CUDA_VISIBLE_DEVICES=1 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.15 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.15.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.15.pth

CUDA_VISIBLE_DEVICES=2 python train_fusion_slim_finetune.py --cfg_file /media/zjurobot/403/yangjingru/pcdet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /media/zjurobot/403/yangjingru/pcdet/benchmark/pp_fusion_early_8_slim0.1 --slimming_json /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_description_0.1.json --slimming_pth /media/zjurobot/403/yangjingru/pcdet/benchmark/slim_fusion_description/slim_model_0.1.pth

CUDA_VISIBLE_DEVICES=1 python train_fusion_slim_finetune.py --cfg_file /home/mk/OpenPCDet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /home/mk/OpenPCDet/benchmark/pp_fusion_early_8_slim0.05 --slimming_json /home/mk/OpenPCDet/benchmark/slim_fusion_description/slim_description_0.05.json --slimming_pth /home/mk/OpenPCDet/benchmark/slim_fusion_description/slim_model_0.05.pth

CUDA_VISIBLE_DEVICES=0 python train_fusion_slim_finetune.py --cfg_file /home/mk/OpenPCDet/tools/cfgs/kitti_models/pointpillar_fusion_early_8.yaml --output /home/mk/OpenPCDet/benchmark/pp_fusion_early_8_slim0.1 --slimming_json /home/mk/OpenPCDet/benchmark/slim_fusion_description/slim_description_0.1.json --slimming_pth /home/mk/OpenPCDet/benchmark/slim_fusion_description/slim_model_0.1.pth